# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carbonio-message-dispatcher
  title: Carbonio Message Dispatcher service
  description: |
    Service that allows to write and store chat messages
    with XMPP protocol thanks to the MongooseIm application.
  tags:
    - bash
    - envoy
    - java
    - backend
  links:
    - url: https://github.com/Zextras/carbonio-message-dispatcher-ce/blob/main/README.md
      title: README
spec:
  type: service
  lifecycle: production
  owner: smoky-beans
  dependsOn:
    - component:carbonio-message-dispatcher-db