<?xml version="1.0" encoding="UTF-8"?>

<!--
SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <packaging>pom</packaging>

  <groupId>com.zextras.carbonio.message.dispatcher</groupId>
  <artifactId>carbonio-message-dispatcher</artifactId>
  <version>${revision}${changelist}</version>

  <modules>
    <module>carbonio-message-dispatcher-auth</module>
  </modules>

  <repositories>
    <repository>
      <id>artifactory</id>
      <name>Zextras releases</name>
      <url>https://zextras.jfrog.io/artifactory/public-maven-repo</url>
    </repository>

    <repository>
      <id>snapshots-repo</id>
      <url>https://repo.zextras.io/maven/snapshot/</url>
    </repository>

    <repository>
      <id>releases-repo</id>
      <url>https://repo.zextras.io/maven/release/</url>
    </repository>
  </repositories>

  <profiles>
    <profile>
      <id>dev</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <changelist>-SNAPSHOT</changelist>
      </properties>
    </profile>
    <profile>
      <id>prod</id>
      <properties>
        <changelist></changelist>
      </properties>
    </profile>
  </profiles>

  <properties>
    <!-- Maven CI Friendly properties -->
    <revision>1.2.4</revision>
    <!-- SonarQube -->
    <sonar.projectKey>com.zextras.carbonio.message.dispatcher:carbonio-message-dispatcher-ce</sonar.projectKey>
    <!-- Dependencies -->
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- Carbonio User Management -->
    <carbonio-user-management-grpc-sdk.version>1.0.3-dev.21.79fc3fa2</carbonio-user-management-grpc-sdk.version>
    <!-- gRPC -->
    <io.grpc.version>1.82.0</io.grpc.version>
    <!-- Database -->
    <flyway-database-postgresql.version>11.8.1</flyway-database-postgresql.version>
    <postgresql.version>42.7.11</postgresql.version>
    <!-- Jetty -->
    <org.eclipse.jetty.version>12.0.25</org.eclipse.jetty.version>
    <org.eclipse.jetty.servlet.version>12.0.25</org.eclipse.jetty.servlet.version>
    <!-- Consul Client -->
    <consul-client.version>1.5.3</consul-client.version>
    <!-- Guice -->
    <guice.version>7.0.0</guice.version>
    <!-- Guava -->
    <guava.version>33.2.1-jre</guava.version>
    <!-- Logging -->
    <org.slf4j-api.version>2.0.17</org.slf4j-api.version>
    <logback-classic.version>1.5.18</logback-classic.version>
    <!-- Plugins -->
    <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
    <maven-shade-plugin.version>3.6.2</maven-shade-plugin.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.inject</groupId>
        <artifactId>guice</artifactId>
        <version>${guice.version}</version>
      </dependency>

      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>${guava.version}</version>
      </dependency>

      <dependency>
        <groupId>com.orbitz.consul</groupId>
        <artifactId>consul-client</artifactId>
        <version>${consul-client.version}</version>
        <exclusions>
          <exclusion>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
          </exclusion>
        </exclusions>
      </dependency>

      <!-- Database -->
      <dependency>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-database-postgresql</artifactId>
        <version>${flyway-database-postgresql.version}</version>
      </dependency>

      <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>${postgresql.version}</version>
      </dependency>

      <!-- Carbonio User Management -->
      <dependency>
        <groupId>com.zextras.carbonio.user-management</groupId>
        <artifactId>carbonio-user-management-grpc-sdk</artifactId>
        <version>${carbonio-user-management-grpc-sdk.version}</version>
      </dependency>

      <!-- gRPC dependencies -->
      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-netty-shaded</artifactId>
        <version>${io.grpc.version}</version>
      </dependency>

      <!-- Jetty dependencies -->
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-server</artifactId>
        <version>${org.eclipse.jetty.version}</version>
      </dependency>

      <dependency>
        <groupId>org.eclipse.jetty.ee10</groupId>
        <artifactId>jetty-ee10-servlet</artifactId>
        <version>${org.eclipse.jetty.servlet.version}</version>
      </dependency>

      <!-- Logging dependencies-->
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${org.slf4j-api.version}</version>
      </dependency>

      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>${logback-classic.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>${maven-shade-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
