#!/bin/bash

# SPDX-FileCopyrightText: 2022 2021 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# decrypt the bootstrap token, asking the password to the sys admin
# --setup check for SETUP_CONSUL_TOKEN env. variable and uses it
# to avoid re-asking for the password
if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

if [[ "$1" != "setup" ]]; then
  echo "Syntax: 'carbonio-chats-messaging setup' to automatically configure the service"
  exit 1;
fi

config_variant() {
  VARIANT=$1
  consul config write /etc/carbonio/chats-messaging/service-discover/service-protocol-"${VARIANT}".json
  consul config write /etc/carbonio/chats-messaging/service-discover/intentions-"${VARIANT}".json
}

# Decrypt the bootstrap token, asking the password to the sys admin
# --setup check for SETUP_CONSUL_TOKEN env. variable and uses it
# to avoid re-asking for the password
echo -n "Insert the cluster credential password: "
export CONSUL_HTTP_TOKEN=$(service-discover bootstrap-token --setup)
EXIT_CODE="$?"
echo ""
if [[ "${EXIT_CODE}" != "0" ]]; then
  echo "Cannot access to bootstrap token"
  exit 1;
fi
# Limit secret visibility as much as possible
export -n SETUP_CONSUL_TOKEN

POLICY_NAME='carbonio-chats-messaging-policy'
POLICY_DESCRIPTION='Carbonio messaging policy for service and sidecar proxy'

# Create or update policy for the specific service (this will be shared across cluster)
consul acl policy create -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules  @/etc/carbonio/chats-messaging/service-discover/policies.json >/dev/null 2>&1
if [[ "$?" != "0" ]]; then
    consul acl policy update -no-merge -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules @/etc/carbonio/chats-messaging/service-discover/policies.json
    if [[ "$?" != "0" ]]; then
      echo "Setup failed: Cannot update policy for ${POLICY_NAME}"
      exit 1
    fi
fi

trap 'echo Script for chats messaging terminated with error' EXIT
set -e

config_variant "http"
config_variant "xmpp"

if [[ ! -f "/etc/carbonio/chats-messaging/service-discover/token" ]]; then
    # Create the token, this is unique for every variant
    consul acl token create -format json -policy-name "${POLICY_NAME}" -description "Token for
    carbonio-chats-messaging/$(hostname -A)" |
      jq -r '.SecretID' > /etc/carbonio/chats-messaging/service-discover/token;
    chown carbonio-chats-messaging:carbonio-chats-messaging /etc/carbonio/chats-messaging/service-discover/token
    chmod 0600 /etc/carbonio/chats-messaging/service-discover/token

    # To pass the token to consul we need to inject it to a env. variable
    # since it doesn't accept a file as an argument
    mkdir -p /etc/systemd/system/carbonio-chats-messaging.service.d/
    cat >/etc/systemd/system/carbonio-chats-messaging.service.d/override.conf <<EOF
[Service]
Environment="CONSUL_HTTP_TOKEN=$(cat /etc/carbonio/chats-messaging/service-discover/token)"
EOF
    chmod 0600 /etc/systemd/system/carbonio-chats-messaging.service.d/override.conf
    systemctl daemon-reload
fi

consul reload

# Limit token visibility as much as possible
export -n CONSUL_HTTP_TOKEN

systemctl restart carbonio-chats-messaging.service
systemctl restart carbonio-chats-messaging-http-sidecar.service
systemctl restart carbonio-chats-messaging-xmpp-sidecar.service
trap - EXIT